name: CI Build
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    container: roscopeco/rosco_m68k:latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v1
        - name: Hack GITHUB_WORKSPACE 🥷
          run: |
            sudo chown -R linuxbrew "$GITHUB_WORKSPACE"
        - name: Build firmware
          run: |
            cd code/firmware/rosco_m68k_firmware
            make clean all
        - name: Build software
          run: |
            cd ../../software
            make clean all

